name: Import Directory

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository URL'
        required: true
        default: 'https://github.com/okxlin/appstore'
      branch:
        description: 'Branch'
        required: true
        default: 'localApps'
      directory:
        description: 'Directory to import'
        required: true
        default: 'apps/mtab'
      target:
        description: 'Target directory'
        required: true
        default: 'apps/mtab'

jobs:
  import-directory:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Import specified directory
      run: |
        git clone --depth 1 --branch ${{ github.event.inputs.branch }} ${{ github.event.inputs.repo }} temp-repo
        rm -rf ${{ github.event.inputs.target }}
        mv temp-repo/${{ github.event.inputs.directory }} ${{ github.event.inputs.target }}
        rm -rf temp-repo

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name 'Akuma-real'
        git config --global user.email 'adminlaowang@stu.cwxu.edu.cn'
        git add ${{ github.event.inputs.target }}
        git commit -m "Import ${{ github.event.inputs.directory }} from ${{ github.event.inputs.repo }}:${{ github.event.inputs.branch }}"
        git push https://${GH_TOKEN}@github.com/Akuma-real/1Panel-AppStore.git HEAD:${{ github.ref }}
